completed

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -46,6 +46,17 @@ variables:                         &default-vars
   VAULT_AUTH_PATH:                 "gitlab-parity-io-jwt"
   VAULT_AUTH_ROLE:                 "cicd_gitlab_parity_${CI_PROJECT_NAME}"
 
+.gen-rustdoc-vars:                 &gen-rustdoc-vars
+  DOC_INDEX_PAGE:                  "sc_service/index.html" # default redirected page
+  # Space separated values of branches and tags to generate rustdocs
+  RUSTDOCS_DEPLOY_REFS:            "master monthly-2021-09+1"
+  # Location of the docs index template
+  INDEX_TPL:                       ".maintain/docs-index-tpl.ejs"
+  # Where the `/latest` symbolic link links to. One of the $RUSTDOCS_DEPLOY_REFS value.
+  LATEST:                          "monthly-2021-09+1"
+  GIT_DEPTH:                       100
+  SKIP_WASM_BUILD:                 1
+
 default:
   cache:                           {}
 
@@ -150,6 +161,20 @@ default:
     # this job runs only on nightly pipeline with the mentioned variable, against `master` branch
     - if: $CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE == "schedule" && $PIPELINE == "nightly"
 
+.gen-rustdoc-rules:                &gen-rustdoc-rules
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "pipeline"
+      when: never
+    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_NAME == "master"
+    - if: $CI_COMMIT_REF_NAME == "master"
+    - if: $CI_COMMIT_REF_NAME =~ /^monthly-20[0-9]{2}-[0-9]{2}.*$/  # to support: monthly-2021-09+1
+    - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1
+
+.regen-all-rustdoc-rules:          &regen-all-rustdoc-rules
+  rules:
+    # Will only run if manually triggered on web with $REPUBLISH_ALL_RUSTDOCS set to true
+    - if: $CI_PIPELINE_SOURCE == "web" && $REPUBLISH_ALL_RUSTDOCS == "true"
+
 .merge-ref-into-master-script:     &merge-ref-into-master-script
   - if [ $CI_COMMIT_REF_NAME != "master" ]; then
       git fetch origin +master:master;
@@ -167,6 +192,37 @@ default:
   - 'cargo run --release -p node-bench -- ::trie::read::small --json
     | tee artifacts/benches/$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA/::trie::read::small.json'
   - sccache -s
+
+.reset-gh-info-script:             &reset-gh-info-script
+  # Reset git config
+  - rm -rf .git/config
+  - git config user.email "devops-team@parity.io"
+  - git config user.name "${GITHUB_USER}"
+  - git config remote.origin.url "https://${GITHUB_TOKEN}@github.com/paritytech/${CI_PROJECT_NAME}.git"
+  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
+  - git fetch origin
+
+.git-force-push-rm-script:         &git-force-push-rm-script
+  # Upload files
+  - git add --all --force
+  # `git commit` has an exit code of > 0 if there is nothing to commit.
+  # This causes GitLab to exit immediately and marks this job failed.
+  # We don't want to mark the entire job failed if there's nothing to
+  # publish though, hence the `|| true`.
+  - git commit -m "___Updated docs for ${CI_COMMIT_REF_NAME}___" || echo "___Nothing to commit___"
+  - git push origin gh-pages --force
+  - rm -rf .git/ ./*
+
+.gen-index-script:                 &gen-index-script
+  # Install `ejs` and generate index.html based on RUSTDOCS_DEPLOY_REFS
+  - yarn global add ejs
+  - 'ejs ${INDEX_TPL} -i "{\"deploy_refs\":\"${RUSTDOCS_DEPLOY_REFS}\",\"repo_name\":\"${CI_PROJECT_NAME}\",\"latest\":\"${LATEST}\"}" > /tmp/index.html'
+
+.cargo-doc-script:                 &cargo-doc-script
+  # FIXME: it fails with `RUSTDOCFLAGS="-Dwarnings"`
+  # Try to run with nightly rustc first. If failed, when use the stable rustc.
+  - RUSTDOCFLAGS="--html-in-header $(pwd)/.maintain/rustdoc-header.html" &&
+    time cargo +nightly doc --no-deps --workspace --all-features --verbose
 
 #### Vault secrets
 .vault-secrets:                    &vault-secrets
@@ -605,20 +661,19 @@ build-rustdoc:
   stage:                           build
   <<:                              *docker-env
   <<:                              *test-refs
+  <<:                              *gen-rustdoc-rules
   variables:
     <<:                            *default-vars
-    SKIP_WASM_BUILD:               1
-    DOC_INDEX_PAGE:                "sc_service/index.html" # default redirected page
+    <<:                            *gen-rustdoc-vars
   artifacts:
     name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}-doc"
     when:                          on_success
     expire_in:                     7 days
     paths:
-    - ./crate-docs/
+      - ./crate-docs/
   script:
-    # FIXME: it fails with `RUSTDOCFLAGS="-Dwarnings"`
-    - RUSTDOCFLAGS="--html-in-header $(pwd)/.maintain/rustdoc-header.html"
-        time cargo +nightly doc --no-deps --workspace --all-features --verbose
+    - '[[ " ${RUSTDOCS_DEPLOY_REFS} " =~ " ${CI_COMMIT_REF_NAME} " ]] || exit 0'
+    - *cargo-doc-script
     - rm -f ./target/doc/.lock
     - mv ./target/doc ./crate-docs
     # FIXME: remove me after CI image gets nonroot
@@ -630,29 +685,36 @@ rebuild-all-rustdoc:
   stage:                           build
   <<:                              *docker-env
   <<:                              *test-refs
+  <<:                              *regen-all-rustdoc-rules
   variables:
     <<:                            *default-vars
-    SKIP_WASM_BUILD:               1
-    DOC_INDEX_PAGE:                "sc_service/index.html" # default redirected page
+    <<:                            *gen-rustdoc-vars
   artifacts:
     name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}-doc"
     when:                          on_success
     expire_in:                     7 days
     paths:
-    - ./crate-docs/
-  rules:
-    # Will only run if manually triggered on web with $REPUBLISH_ALL_RUSTDOCS set to true
-    - if: $CI_PIPELINE_SOURCE == "web" && $REPUBLISH_ALL_RUSTDOCS == "true"
-  artifacts:
-    name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}-doc"
-    when:                          on_success
-    expire_in:                     7 days
-    paths:
-    - ./crate-docs/
+      - ./crate-docs/
   script:
-
-
-
+    - *reset-gh-info-script
+    - mkdir crate-docs
+    - DEPLOY_ARR=($RUSTDOCS_DEPLOY_REFS)
+    - for REF in "${DEPLOY_ARR[@]}"; do
+        git checkout $REF || (echo "${REF} not existed in remote." && continue);
+        echo "Checked out $REF";
+        RUSTDOCFLAGS="--html-in-header $(pwd)/.maintain/rustdoc-header.html" && (
+          time cargo +nightly doc --no-deps --workspace --all-features --verbose ||
+          echo "Generate $REF rustdocs failed"
+        );
+        [[ -e ./target/doc ]] || continue;
+        rm -f ./target/doc/.lock;
+        mv target/doc crate-docs/${REF};
+        echo "<meta http-equiv=refresh content=0;url=${DOC_INDEX_PAGE}>" > ./crate-docs/${REF}/index.html;
+      done
+    - chown -R nonroot:nonroot ./crate-docs
+    - sccache -s
+  after_script:
+    - rm -rf .git/
 
 #### stage:                        publish
 
@@ -747,23 +809,10 @@ publish-rustdoc:
   stage:                           publish
   <<:                              *kubernetes-env
   <<:                              *vault-secrets
+  <<:                              *gen-rustdoc-rules
   image:                           node:16
   variables:
-    GIT_DEPTH:                     100
-    # --- Following variables are for rustdocs deployment ---
-    # Space separated values of branches and tags to generate rustdocs
-    RUSTDOCS_DEPLOY_REFS:          "master monthly-2021-09+1 monthly-2021-08 v3.0.0"
-    # Location of the docs index template
-    INDEX_TPL:                     ".maintain/docs-index-tpl.ejs"
-    # Where the `/latest` symbolic link links to. One of the $RUSTDOCS_DEPLOY_REFS value.
-    LATEST:                        "monthly-2021-09+1"
-  rules:
-    - if: $CI_PIPELINE_SOURCE == "pipeline"
-      when: never
-    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_NAME == "master"
-    - if: $CI_COMMIT_REF_NAME == "master"
-    - if: $CI_COMMIT_REF_NAME =~ /^monthly-20[0-9]{2}-[0-9]{2}.*$/  # to support: monthly-2021-09+1
-    - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1
+    <<:                            *gen-rustdoc-vars
   # `needs:` can be removed after CI image gets nonroot. In this case `needs:` stops other
   # artifacts from being dowloaded by this job.
   needs:
@@ -776,16 +825,8 @@ publish-rustdoc:
     # whole space-separated value.
     - '[[ " ${RUSTDOCS_DEPLOY_REFS} " =~ " ${CI_COMMIT_REF_NAME} " ]] || exit 0'
     - rm -rf /tmp/*
-    # Set git config
-    - rm -rf .git/config
-    - git config user.email "devops-team@parity.io"
-    - git config user.name "${GITHUB_USER}"
-    - git config remote.origin.url "https://${GITHUB_TOKEN}@github.com/paritytech/${CI_PROJECT_NAME}.git"
-    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
-    - git fetch origin gh-pages
-    # Install `ejs` and generate index.html based on RUSTDOCS_DEPLOY_REFS
-    - yarn global add ejs
-    - 'ejs ${INDEX_TPL} -i "{\"deploy_refs\":\"${RUSTDOCS_DEPLOY_REFS}\",\"repo_name\":\"${CI_PROJECT_NAME}\",\"latest\":\"${LATEST}\"}" > /tmp/index.html'
+    - *reset-gh-info-script
+    - *gen-index-script
     # Save README and docs
     - cp -r ./crate-docs/ /tmp/doc/
     - cp README.md /tmp/doc/
@@ -809,17 +850,31 @@ publish-rustdoc:
     - mv -f /tmp/doc ${CI_COMMIT_REF_NAME}
     # Add the symlink
     - '[[ -e "$LATEST" ]] && ln -sf "${LATEST}" latest'
-    # Upload files
-    - git add --all --force
-    # `git commit` has an exit code of > 0 if there is nothing to commit.
-    # This causes GitLab to exit immediately and marks this job failed.
-    # We don't want to mark the entire job failed if there's nothing to
-    # publish though, hence the `|| true`.
-    - git commit -m "___Updated docs for ${CI_COMMIT_REF_NAME}___" ||
-        echo "___Nothing to commit___"
-    - git push origin gh-pages --force
-  after_script:
-    - rm -rf .git/ ./*
+    - *git-force-push-rm-script
+
+republish-all-rustdoc:
+  stage:                           publish
+  <<:                              *kubernetes-env
+  <<:                              *vault-secrets
+  <<:                              *regen-all-rustdoc-rules
+  image:                           node:16
+  variables:
+    <<:                            *gen-rustdoc-vars
+  needs:
+    - job:                         rebuild-all-rustdoc
+      artifacts:                   true
+  script:
+    - rm -rf /tmp/*
+    - mv crate-docs /tmp/doc
+    - *gen-index-script
+    - *reset-gh-info-script
+    - git checkout gh-pages
+    - rm -rf *
+    - mv -f /tmp/doc/* .
+    - mv -f /tmp/index.html .
+    # Add the symlink
+    - '[[ -e "$LATEST" ]] && ln -sf "${LATEST}" latest'
+    - *git-force-push-rm-script
 
 publish-draft-release:
   stage:                           publish
