Updated
Signed-off-by: Jimmy Chu <jimmychu0807@gmail.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -48,14 +48,13 @@ variables:                         &default-vars
   SIMNET_FEATURES_PATH:            "simnet_tests/tests"
   PIPELINE_SCRIPTS_TAG:            "v0.1"
 
-.gen-rustdoc-vars:                 &gen-rustdoc-vars
-  DOC_INDEX_PAGE:                  "sc_service/index.html" # default redirected page
+.build-rustdoc-vars:               &build-rustdoc-vars
   # Space separated values of branches and tags to generate rustdocs
-  RUSTDOCS_DEPLOY_REFS:            "master monthly-2021-09+1"
-  # Location of the docs index template
-  INDEX_TPL:                       ".maintain/docs-index-tpl.ejs"
+  CONT_RUSTDOC_BUILT_REFS:         "master"
+  REPO_URL:                        "https://${GITHUB_TOKEN}@github.com/paritytech/substrate.git"
+  DOC_INDEX_PAGE:                  "sc_service/index.html" # default redirected page
   # Where the `/latest` symbolic link links to. One of the $RUSTDOCS_DEPLOY_REFS value.
-  LATEST:                          "monthly-2021-09+1"
+  LATEST:                          "monthly-2021-10"
   GIT_DEPTH:                       100
   SKIP_WASM_BUILD:                 1
 
@@ -171,19 +170,16 @@ default:
     # this job runs only on nightly pipeline with the mentioned variable, against `master` branch
     - if: $CI_COMMIT_REF_NAME == "master" && $CI_PIPELINE_SOURCE == "schedule" && $PIPELINE == "nightly"
 
-.gen-rustdoc-rules:                &gen-rustdoc-rules
-  rules:
-    - if: $CI_PIPELINE_SOURCE == "pipeline"
-      when: never
-    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_NAME == "master"
-    - if: $CI_COMMIT_REF_NAME == "master"
-    - if: $CI_COMMIT_REF_NAME =~ /^monthly-20[0-9]{2}-[0-9]{2}.*$/  # to support: monthly-2021-09+1
-    - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1
+.build-rustdoc-rules:              &build-rustdoc-rules
+  - if: $CI_PIPELINE_SOURCE == "pipeline"
+    when: never
+  - if: $CI_PIPELINE_SOURCE == "web" && $RM_RUSTDOC_REF
+    when: never
+  - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "push" ||
+      ($CI_PIPELINE_SOURCE == "web" && $BUILD_RUSTDOC_REF)
 
-.regen-all-rustdoc-rules:          &regen-all-rustdoc-rules
-  rules:
-    # Will only run if manually triggered on web with $REPUBLISH_ALL_RUSTDOCS set to true
-    - if: $CI_PIPELINE_SOURCE == "web" && $REPUBLISH_ALL_RUSTDOCS == "true"
+.rm-rustdoc-rules:                 &rm-rustdoc-rules
+  - if: $CI_PIPELINE_SOURCE == "web" && $RM_RUSTDOC_REF
 
 .merge-ref-into-master-script:     &merge-ref-into-master-script
   - if [ $CI_COMMIT_REF_NAME != "master" ]; then
@@ -221,33 +217,48 @@ default:
 .cargo-doc-script:                 &cargo-doc-script
   # FIXME: it fails with `RUSTDOCFLAGS="-Dwarnings"`
   # Try to run with nightly rustc first. If failed, when use the stable rustc.
-  - RUSTDOCFLAGS="--html-in-header $(pwd)/.maintain/rustdoc-header.html" &&
-    time cargo +nightly doc --no-deps --workspace --all-features --verbose
+  - (RUSTDOCFLAGS="--html-in-header $(pwd)/.maintain/rustdoc-header.html" &&
+    time cargo +nightly doc --no-deps --workspace --all-features --verbose) ||
+    { echo "Generate $BUILD_REF rustdocs failed" && exit 0; }
+
+.upsert-index-script:              &upsert-index-script
+  # generate index.html based on BUILD_REF
+  - yarn global add @jimmychu0807/index-tpl-crud
+  - '[[ "${RESET_INDEX}" == "true" ]] && index-tpl-crud init
+    "${GH_REPO:-CI_PROJECT_NAME}" "Substrate" /tmp/index.html'
+  - '[[ "${LATEST}" == "${BUILD_REF}" ]]
+    && index-tpl-crud upsert -l /tmp/index.html ${BUILD_REF}
+    || index-tpl-crud upsert /tmp/index.html ${BUILD_REF}'
+
+.rm-index-script:                  &rm-index-script
+  - yarn global add @jimmychu0807/index-tpl-crud
+  - index-tpl-crud rm /tmp/index.html ${RM_RUSTDOC_REF}
 
 .reset-gh-info-script:             &reset-gh-info-script
   # Reset git config
   - rm -rf .git/config
   - git config user.email "devops-team@parity.io"
   - git config user.name "${GITHUB_USER}"
-  - git config remote.origin.url "https://${GITHUB_TOKEN}@github.com/paritytech/${CI_PROJECT_NAME}.git"
+  - git config remote.origin.url "${REPO_URL}"
   - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
   - git fetch origin
 
 .git-force-push-rm-script:         &git-force-push-rm-script
-  # Upload files
+  # push it back to github gh-pages
   - git add --all --force
-  # `git commit` has an exit code of > 0 if there is nothing to commit.
-  # This causes GitLab to exit immediately and marks this job failed.
-  # We don't want to mark the entire job failed if there's nothing to
-  # publish though, hence the `|| true`.
   - git commit -m "___Updated docs for ${CI_COMMIT_REF_NAME}___" || echo "___Nothing to commit___"
   - git push origin gh-pages --force
   - rm -rf .git/ ./*
 
-.gen-index-script:                 &gen-index-script
-  # Install `ejs` and generate index.html based on RUSTDOCS_DEPLOY_REFS
-  - yarn global add ejs
-  - 'ejs ${INDEX_TPL} -i "{\"deploy_refs\":\"${RUSTDOCS_DEPLOY_REFS}\",\"repo_name\":\"${CI_PROJECT_NAME}\",\"latest\":\"${LATEST}\"}" > /tmp/index.html'
+.test-build-rustdoc:  &test-build-rustdoc
+  # The actual check on whether we need to build rustdocs. This task will run if it is one of
+  #   branch/tag in CONT_RUSTDOC_BUILT_REFS or triggered via web with BUILD_RUSTDOC_REF set to
+  #   a branch/tag name.
+  - '[[ " ${CONT_RUSTDOC_BUILT_REFS} " =~ " ${CI_COMMIT_REF_NAME} " || -n "${BUILD_RUSTDOC_REF}" ]]
+    || { echo "No rustdoc built." && exit 0; }'
+  - '[[ -n ${BUILD_RUSTDOC_REF} ]]
+    && BUILD_REF=${BUILD_RUSTDOC_REF}
+    || BUILD_REF=${CI_COMMIT_REF_NAME}'
 
 #### Vault secrets
 .vault-secrets:                    &vault-secrets
@@ -642,7 +653,6 @@ check-dependent-cumulus:
   variables:
     DEPENDENT_REPO: cumulus
 
-
 build-linux-substrate:
   stage:                           build
   <<:                              *collect-artifacts
@@ -657,7 +667,6 @@ build-linux-substrate:
     - *build-linux-substrate-script
     - printf '\n# building node-template\n\n'
     - ./.maintain/node-template-release.sh ./artifacts/substrate/substrate-node-template.tar.gz
-
 
 #Build binary for simnet quick tests.
 build-linux-substrate-simnet:
@@ -702,60 +711,33 @@ build-rustdoc:
   stage:                           build
   <<:                              *docker-env
   <<:                              *test-refs
-  <<:                              *gen-rustdoc-rules
+  rules:
+    - *build-rustdoc-rules
   variables:
     <<:                            *default-vars
-    <<:                            *gen-rustdoc-vars
+    <<:                            *build-rustdoc-vars
   artifacts:
     name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}-doc"
     when:                          on_success
     expire_in:                     7 days
     paths:
-      - ./crate-docs/
+      - crate-docs
   script:
-    - '[[ " ${RUSTDOCS_DEPLOY_REFS} " =~ " ${CI_COMMIT_REF_NAME} " ]] || exit 0'
+    - *test-build-rustdoc
+    # Check if we are at the right branch/tag. if not check out the branch
+    - if [[ -n "${BUILD_RUSTDOC_REF}" ]]; then
+        git fetch --all;
+        git checkout -f $BUILD_RUSTDOC_REF ||
+          { echo "Checkout ${BUILD_RUSTDOC_REF} error." && exit 0; };
+      fi
     - *cargo-doc-script
     - rm -f ./target/doc/.lock
-    - mv ./target/doc ./crate-docs
-    # FIXME: remove me after CI image gets nonroot
-    - chown -R nonroot:nonroot ./crate-docs
-    - echo "<meta http-equiv=refresh content=0;url=${DOC_INDEX_PAGE}>" > ./crate-docs/index.html
-    - sccache -s
-
-rebuild-all-rustdoc:
-  stage:                           build
-  <<:                              *docker-env
-  <<:                              *test-refs
-  <<:                              *regen-all-rustdoc-rules
-  variables:
-    <<:                            *default-vars
-    <<:                            *gen-rustdoc-vars
-  artifacts:
-    name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}-doc"
-    when:                          on_success
-    expire_in:                     7 days
-    paths:
-      - ./crate-docs/
-  script:
-    - *reset-gh-info-script
     - mkdir crate-docs
-    - DEPLOY_ARR=($RUSTDOCS_DEPLOY_REFS)
-    - for REF in "${DEPLOY_ARR[@]}"; do
-        git checkout $REF || (echo "${REF} not existed in remote." && continue);
-        echo "Checked out $REF";
-        RUSTDOCFLAGS="--html-in-header $(pwd)/.maintain/rustdoc-header.html" && (
-          time cargo +nightly doc --no-deps --workspace --all-features --verbose ||
-          echo "Generate $REF rustdocs failed"
-        );
-        [[ -e ./target/doc ]] || continue;
-        rm -f ./target/doc/.lock;
-        mv target/doc crate-docs/${REF};
-        echo "<meta http-equiv=refresh content=0;url=${DOC_INDEX_PAGE}>" > ./crate-docs/${REF}/index.html;
-      done
-    - chown -R nonroot:nonroot ./crate-docs
+    - mv target/doc crate-docs/${BUILD_REF}
+    # FIXME: remove me after CI image gets nonroot
+    - chown -R nonroot:nonroot crate-docs
+    - echo "<meta http-equiv=refresh content=0;url=${DOC_INDEX_PAGE}>" > crate-docs/${BUILD_REF}/index.html
     - sccache -s
-  after_script:
-    - rm -rf .git/
 
 #### stage:                        publish
 
@@ -869,71 +851,55 @@ publish-rustdoc:
   stage:                           publish
   <<:                              *kubernetes-env
   <<:                              *vault-secrets
-  <<:                              *gen-rustdoc-rules
-  image:                           node:16
-  variables:
-    <<:                            *gen-rustdoc-vars
   # `needs:` can be removed after CI image gets nonroot. In this case `needs:` stops other
   # artifacts from being dowloaded by this job.
   needs:
     - job:                         build-rustdoc
       artifacts:                   true
+  variables:
+    <<:                            *default-vars
+    <<:                            *build-rustdoc-vars
+  rules:
+    - *build-rustdoc-rules
+  image:                           node:16
   script:
-    # If $CI_COMMIT_REF_NAME doesn't match one of $RUSTDOCS_DEPLOY_REFS space-separated values, we
-    # exit immediately.
-    # Putting spaces at the front and back to ensure we are not matching just any substring, but the
-    # whole space-separated value.
-    - '[[ " ${RUSTDOCS_DEPLOY_REFS} " =~ " ${CI_COMMIT_REF_NAME} " ]] || exit 0'
+    - *test-build-rustdoc
     - rm -rf /tmp/*
+    - mv -f crate-docs/${BUILD_REF} /tmp/docs
     - *reset-gh-info-script
-    - *gen-index-script
-    # Save README and docs
-    - cp -r ./crate-docs/ /tmp/doc/
-    - cp README.md /tmp/doc/
-    - git checkout gh-pages
-    # Remove directories no longer necessary, as specified in $RUSTDOCS_DEPLOY_REFS.
-    # Also ensure $RUSTDOCS_DEPLOY_REFS is not just empty spaces.
-    # Even though this block spans multiple lines, they are concatenated to run as a single line
-    #   command, so note for the semi-colons in the inner-most code block.
-    - if [[ ! -z ${RUSTDOCS_DEPLOY_REFS// } ]]; then
-        for FILE in *; do
-          if [[ ! " $RUSTDOCS_DEPLOY_REFS " =~ " $FILE " ]]; then
-            echo "Removing ${FILE}...";
-            rm -rf $FILE;
-          fi
-        done
-      fi
-    # Move the index page & built back
+    - git checkout -f gh-pages
+    # Upsert <li/> entry into the index.html
+    - cp index.html /tmp
+    - *upsert-index-script
     - mv -f /tmp/index.html .
-    # Ensure the destination dir doesn't exist.
-    - rm -rf ${CI_COMMIT_REF_NAME}
-    - mv -f /tmp/doc ${CI_COMMIT_REF_NAME}
+    # Ensure the destination dir is clear
+    - rm -rf ${BUILD_REF}
+    - mv -f /tmp/docs ${BUILD_REF}
     # Add the symlink
-    - '[[ -e "$LATEST" ]] && ln -sf "${LATEST}" latest'
+    - '[[ -e "$LATEST" ]] && { [[ -h latest ]] && rm latest; ln -sf "${LATEST}" latest; }'
     - *git-force-push-rm-script
 
-republish-all-rustdoc:
+rm-rustdoc:
   stage:                           publish
   <<:                              *kubernetes-env
   <<:                              *vault-secrets
-  <<:                              *regen-all-rustdoc-rules
-  image:                           node:16
   variables:
-    <<:                            *gen-rustdoc-vars
-  needs:
-    - job:                         rebuild-all-rustdoc
-      artifacts:                   true
+    <<: *default-vars
+    <<: *build-rustdoc-vars
+  rules:
+    - *rm-rustdoc-rules
+  image:                           node:16
   script:
-    - rm -rf /tmp/*
-    - mv crate-docs /tmp/doc
-    - *gen-index-script
     - *reset-gh-info-script
-    - git checkout gh-pages
-    - rm -rf *
-    - mv -f /tmp/doc/* .
+    - git checkout -f gh-pages
+    # Rm <li/> entry from the index.html
+    - cp index.html /tmp
+    - *rm-index-script
     - mv -f /tmp/index.html .
-    # Add the symlink
-    - '[[ -e "$LATEST" ]] && ln -sf "${LATEST}" latest'
+    # Remove the dir
+    - rm -rf ${RM_RUSTDOC_REF}
+    # Remove the symlink
+    - '[[ -h latest && "$(readlink latest)" == "${RM_RUSTDOC_REF}" ]] && rm latest'
     - *git-force-push-rm-script
 
 publish-draft-release:
