debug (ci): shouldn't require repo [skip ci]

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -745,7 +745,25 @@ variables:
       - $BRANCH_NAME
       # - $JOB_NAME
   script:
-    - .maintain/gitlab/purge_cache.sh
+    - |
+      if [ -n "${PROJECT_NAME}" ] && [ -n "${CACHE_TYPE}" ] && [ -n "${BRANCH_NAME}" ]
+      then
+          if [ -d "/ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME}/${JOB_NAME}" ]
+          then
+              echo "Purging JOB cache in /ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME}/${JOB_NAME} .";
+              ls -l "/ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME}";
+          elif [ -d "/ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME}" ]
+          then
+              echo "Purging BRANCH cache in /ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME} .";
+              ls -l "/ci-cache/${PROJECT_NAME}/${CACHE_TYPE}";
+          else
+              echo "Error! Directory /ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME} does not exist.";
+              exit 1;
+          fi
+      else
+          echo "Please set necessary variables.";
+          exit 1;
+      fi    
 
 purge_cache 2 8:
   <<:                              *purge_cache
