debug (ci): check necessary variables [skip ci]

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -745,9 +745,24 @@ variables:
       - $BRANCH_NAME
       # - $JOB_NAME
   script:
-    - echo 'Purging "/ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME}/${JOB_NAME}" cache'
-    - ls -l "/ci-cache/${PROJECT_NAME}/${CACHE_TYPE}"
-    - ls -l "/ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME}"
+    - if [ -n "${PROJECT_NAME}" ] && [ -n "${CACHE_TYPE}" ] && [ -n "${BRANCH_NAME}" ] 
+      then
+          if [ -d "/ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME}/${JOB_NAME}" ]
+          then
+              echo "Purging JOB cache in /ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME}/${JOB_NAME} .";
+              ls -l "/ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME}";
+          elif [ -d "/ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME}" ]
+          then
+              echo "Purging BRANCH cache in /ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME} .";
+              ls -l "/ci-cache/${PROJECT_NAME}/${CACHE_TYPE}";
+          else
+              echo "Error! Directory /ci-cache/${PROJECT_NAME}/${CACHE_TYPE}/${BRANCH_NAME} does not exist.";
+              exit 1;
+          fi
+      else
+          echo "Please set necessary variables.";
+          exit 1;
+      fi
 
 purge_cargo_home 2 8:
   <<:                              *purge_cargo_home
@@ -769,15 +784,7 @@ purge_cargo_home 6 8:
   tags:
     - ci6
 
-# purge_cargo_home 8 8:
-#   <<:                              *purge_cargo_home
-#   tags:
-#     - ci8
-
-purge_cargo_home_all:
+purge_cargo_home 8 8:
   <<:                              *purge_cargo_home
   tags:
-    - ci2
-    - ci3
-    - ci5
-    - ci6
+    - ci8
